// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiduxammdscacaghfzuj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpZHV4YW1tZHNjYWNhZ2hmenVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxOTUzMzcsImV4cCI6MjA4NDc3MTMzN30.2vaeqpSbd7gbqM8I9PZ4po43zVuP00T-hbMENSaqrNI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});